Management of student projects/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("accounts.urls")),
    path('administrators/', include("administration.urls")),
    path('admin/', admin.site.urls),
    path('teachers/', include("teachers.urls")),
    path('students/', include("students.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'accounts.views.handler404'

Management of student projects/teachers/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('student-permissions', views.student_permissions, name="t_student_permissions"),
    path('create-project', views.create_project, name="t_create_project"),
    path('projects-list', views.projects_list, name="t_projects_list"),
    path('students-list', views.students_list, name="t_students_list"),
    path('students-list/delete/<id>', views.delete_student, name="t_delete_student"),
    path('suggestions-list', views.suggestions_list, name="t_suggestions_list"),
    path('suggestions-list/confirm/<id>', views.confirm_suggestion, name="t_confirm_suggestion"),
    path('reports_list', views.reports_list, name="t_reports_list"),
    path('reports_list/<id>', views.report_detail, name="t_report_detail"),
    path('final-reports-list', views.final_reports_list, name="t_final_reports_list"),
    path('final-reports-list/<id>', views.final_report_detail, name="t_final_report_detail"),
    path('archive-report-list', views.archive_report_list, name="t_archive_report_list"),
    path('archive-report-list/<id>', views.archive_report_detail, name="t_archive_report_detail"),
]

Management of student projects/administration/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

PROJECT_TYPE_CHOISES = (
    ("web", "تحت وب"),
    ("desktop", "دسکتاپ"),
    ("mobile", "موبایل"),
)

PROJECT_MEMBER_CHOISES = (
    (1, "یک"),
    (2, "دو"),
    (3, "سه"),
)


class Project(models.Model):
    title = models.CharField(max_length=255)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=150, choices=PROJECT_TYPE_CHOISES)
    number_of_students = models.IntegerField(choices=PROJECT_MEMBER_CHOISES)
    description = models.TextField()
    is_suggested = models.BooleanField(default=False)

    def __str__(self):
        return self.title

Management of student projects/teachers/models.py
from django.db import models
from accounts.models import CollegeUsers
from administration.models import Project

# Create your models here.


class ProjectSetting(models.Model):
    can_get = models.BooleanField()
    suggest = models.BooleanField()
    reports = models.BooleanField()
    final_report = models.BooleanField()

    def __str__(self):
        return "برای تغییر ضربه بزنید"


class ReportParts(models.Model):
    number = models.IntegerField()
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f"Part {self.number}"


class ProjectReport(models.Model):
    student = models.ForeignKey(CollegeUsers, on_delete=models.CASCADE)
    number = models.IntegerField()
    file = models.FileField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    mark = models.IntegerField(null=True, blank=True)
    date = models.DateField(auto_now=True)
    is_submit = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.student} - {self.number}"


class FinalReport(models.Model):
    student = models.ForeignKey(CollegeUsers, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    file = models.FileField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    mark = models.IntegerField(null=True, blank=True)
    is_archive = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.student}"

Management of student projects/teachers/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from administration.models import Project
from accounts.models import CollegeUsers
from .models import ProjectSetting, ReportParts, ProjectReport, FinalReport
from django.contrib.auth.models import User

from teachers import models

# Create your views here.


def student_permissions(request):
    project = ProjectSetting.objects.filter(id=1)
    if request.method == "POST":
        can_get = False if not request.POST.get("can_get") else True
        suggest = False if not request.POST.get("suggest") else True
        reports = False if not request.POST.get("reports") else True
        final_report = False if not request.POST.get("final_report") else True
        if project:
            project.update(can_get=can_get, suggest=suggest, reports=reports, final_report=final_report)
        else:
            ProjectSetting.objects.create(can_get=can_get, suggest=suggest, reports=reports, final_report=final_report)
        return redirect(reverse("t_student_permissions"))
    context = {
        'active_tab': 'student_permissions',
        'settings': project.last(),
    }
    return render(request, 'teachers/Parts Project.html', context)


def create_project(request):
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        title = request.POST.get("title")
        type = request.POST.get("type")
        number_of_students = request.POST.get("number_of_students")
        description = request.POST.get("description")
        Project.objects.create(title=title, creator=user, type=type, number_of_students=number_of_students, description=description, is_suggested=False)
        return redirect("t_create_project")
    context = {
        'active_tab': 'create_project',
    }
    return render(request, 'teachers/Create project.html', context)


def projects_list(request):
    context = {
        'active_tab': 'projects_list',
        'projects': Project.objects.filter(is_suggested=False),
    }
    return render(request, 'teachers/List projects.html', context)


def students_list(request):
    context = {
        'active_tab': 'students_list',
        'students': CollegeUsers.objects.filter(is_student=True),
    }
    return render(request, 'teachers/List Students.html', context)


@login_required
def delete_student(request, id):
    student = get_object_or_404(CollegeUsers, id=id)
    user = User.objects.get(id=student.user.id)
    user.delete()
    return redirect(reverse("t_students_list"))


def suggestions_list(request):
    context = {
        'active_tab': 'suggestions_list',
        'suggestions': Project.objects.filter(is_suggested=True),
    }
    return render(request, 'teachers/List Suggestions.html', context)


def confirm_suggestion(request, id):
    suggestion = get_object_or_404(Project, id=id)
    suggestion.is_suggested = False
    suggestion.save()
    return redirect(reverse("t_suggestions_list"))


def reports_list(request):
    all_part_objects = ReportParts.objects.all()
    if not all_part_objects:
        for r in range(1, 9):
            ReportParts.objects.create(number=r, is_active=True)
        return redirect(reverse('t_reports_list'))
    if request.method == "POST":
        selected = request.POST.getlist("report_number")
        for part in all_part_objects:
            if str(part.id) in selected:
                part.is_active = True
            else:
                part.is_active = False
            part.save()
        return redirect(reverse('t_reports_list'))
    context = {
        'active_tab': 'reports_list',
        'report_parts': all_part_objects,
        'reports': ProjectReport.objects.all(),
    }
    return render(request, 'teachers/List Reports.html', context)


def report_detail(request, id):
    report = get_object_or_404(ProjectReport, id=id)
    if request.method == "POST":
        mark = request.POST.get('mark')
        report.mark = mark
        report.save()
        return redirect(reverse('t_reports_list'))
    context = {
        'active_tab': 'report_detail',
        'report': report,
    }
    return render(request, 'teachers/Reports.html', context)


def final_reports_list(request):
    context = {
        'active_tab': 'final_reports_list',
        'final_reports': FinalReport.objects.filter(is_archive=False)
    }
    return render(request, 'teachers/Final Reports.html', context)


def final_report_detail(request, id):
    report = get_object_or_404(FinalReport, id=id)
    if request.method == "POST":
        mark = request.POST.get('mark')
        description = request.POST.get('description')
        report.mark = mark
        report.description = description
        report.is_archive = True
        report.save()
        return redirect(reverse('t_final_reports_list'))
    context = {
        'active_tab': 'final_report_detail',
        'report': report,
    }
    return render(request, 'teachers/Final.html', context)


def archive_report_list(request):
    context = {
        'active_tab': 'archive_report_list',
        'archive_reports': FinalReport.objects.filter(is_archive=True)
    }
    return render(request, 'teachers/Archive.html', context)


def archive_report_detail(request, id):
    report = get_object_or_404(FinalReport, id=id)
    context = {
        'active_tab': 'archive_report_detail',
        'report': report,
    }
    return render(request, 'teachers/Final Archive.html', context)

Management of student projects/teachers/templates/teachers/Archive.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}بایگانی{% endblock %}
{% block content %}
<!-- بخش اصلی صفحه -->
<section class="main active-side">
    <table class="table table-primary table-striped list-final-report">
        <!-- منو -->
        <tr>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th> موضوع </th>
            <th> پروژه </th>
        </tr>
        <!-- بدنه و ایتم ها -->
        {% for report in archive_reports %}
        <tr>
            <td>{{ report.student.firstname }}</td>
            <td>{{ report.student.lastname }}</td>
            <td>{{ report.project.title }}</td>
            <td>
                <a href="/teachers/archive-report-list/{{ report.id }}"> نمایش </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/Create project.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}ایجاد پروژه{% endblock %}
{% block content %}
<!-- بخش اصلی -->
<section class="main active-side">
    <form class="form" method="post">
        {% csrf_token %}
        <!-- عنوان پروژه -->
        <div class="mb-3">
            <label for="PrpjectName" class="form-label">عنوان پروژه</label>
            <input name="title" type="text" class="form-control" id="PrpjectName">
        </div>
        <!-- انتخاب پلتفرم و تعداد نفرات گروه -->
        <div class="d-flex flex-column flex-md-row justify-content-center mb-3">
            <!-- پلتفرم -->
            <div class="list-group m-1 w-auto">
                <!-- web -->
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="type" value="web" checked>
                    <span>
                        تحت وب
                        <span class="d-block text-muted small">سایت ها و وبسایت هایی که از طریق اینترنت قایل دسترسی
                            هستند</span>
                    </span>
                </label>
                <!-- desktop -->
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="type" value="desktop">
                    <span>
                        دسکتاپ
                        <span class="d-block text-muted small">نرم افزار های ویندوزی برای لپ تاپ و کامپیوتر</span>
                    </span>
                </label>
                <!-- mobile -->
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="type" value="mobile">
                    <span>
                        موبایل
                        <span class="d-block text-muted small">اپیکیشن اندروید برای گوشی های موبایل</span>
                    </span>
                </label>
            </div>
            <!-- تعداد گروه -->
            <div class="list-group m-0 mt-1  w-auto">
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="number_of_students" id="radios1" value="1" checked="">
                    <span>
                        1 نفر
                    </span>
                </label>
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="number_of_students" id="radios2" value="2">
                    <span>
                        2 نفر
                    </span>
                </label>
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="number_of_students" id="radios3" value="3">
                    <span>
                        3 نفر
                    </span>
                </label>
            </div>
        </div>
        <!-- توضیحات پروژه -->
        <div class="mb-3">
            <label for="PrpjectName" class="form-label">توضیحات پروژه</label>
            <textarea name="description" class="form-control" id="PrpjectInfo" cols="5" rows="4"></textarea>
        </div>
        <!-- دکمه ثبت -->
        <button type="submit" class="btn btn-blue w-100 py-2 mb-1">ثبت</button>
        <!-- دکمه پروژه های ایجاد شده -->
        <a href="#" class="btn btn-secondary w-100 py-2">پروژه ها</a>
    </form>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/Final Archive.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}پروژه نهایی{% endblock %}
{% block content %}
<!-- بخش اصلی پروژه -->
<section class="main active-side">
    <div class="form">
        <!-- اطلاعات -->
        <h5 class="mb-3">{{ report.student.firstname }} {{ report.student.lastname }}</h5>
        <p>
            <p class="small bg-primary text-light p-1 px-3 rounded d-inline">
                {{ report.project.title }}
            </p>
            <br><br>
            فایل ها
        </p>
        <!-- فایل ها -->
        <div class="file-drop-area mb-3">
            {% if report.file %}
            <a href="{{ report.file.url }}">{{ report.file }}</a>
            {% else %}
            <span>فایلی موجود نیست</span>
            {% endif %}
        </div>
        <!-- توضیحات -->
        <div class="mb-3">
            <label for="PrpjectDiscripiton" class="form-label">توضیحات اختیاری</label>
            <textarea class="form-control" id="PrpjectDiscripiton" cols="5" rows="4" placeholder="ندارد" disabled>{{ report.description }}</textarea>
        </div>
        <!-- نمره -->
        <div class="mb-3">
            <label for="PrpjectDiscripiton" class="form-label">نمره</label>
            <input type="number" class="form-control w-25" placeholder="0" min="0" max="20" disabled value="{{ report.mark }}">
        </div>
    </div>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/Final Reports.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}گزارش نهایی{% endblock %}
{% block content %}
<!-- بخش اصلی صفحه -->
<section class="main active-side">
    <table class="table table-primary table-striped list-final-report">
        <!-- منو -->
        <tr>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th> گزارش نهایی</th>
        </tr>
        <!-- بدنه و ایتم ها -->
        {% for report in final_reports %}
        <tr>
            <td>{{ report.student.firstname }}</td>
            <td>{{ report.student.lastname }}</td>
            <td>
                <a href="/teachers/final-reports-list/{{ report.id }}"> نمایش </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/Final.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}پروژه نهایی{% endblock %}
{% block content %}
<!-- بخش اصلی پروژه -->
<section class="main active-side">
    <div class="form">
        <!-- اطلاعات -->
        <h5 class="mb-3">{{ report.student.firstname }} {{ report.student.lastname  }}</h5>
        <p>
            <p class="small bg-primary text-light p-1 rounded d-inline">
                گزارش نهایی
            </p>
            <br><br>
            فایل ها
        </p>
        <!-- فایل ها -->
        <div class="file-drop-area mb-3">
            {% if report.file %}
            <a href="{{ report.file.url }}">{{ report.file }}</a>
            {% else %}
            <span>فایلی موجود نیست</span>
            {% endif %}
        </div>
        <form method="post">
            {% csrf_token %}
            <!-- توضیحات -->
            <div class="mb-3">
                <label for="PrpjectDiscripiton" class="form-label">توضیحات اختیاری</label>
                <textarea name="description" class="form-control" id="PrpjectDiscripiton" cols="5" rows="4" placeholder="ندارد">{{ report.description }}</textarea>
            </div>
            <!-- فرم ثبت نمره -->

            <div class="mb-3">
                <label for="PrpjectDiscripiton" class="form-label">نمره</label>
                <input name="mark" type="number" class="form-control w-25" placeholder="ندارد" min="0" max="20" value="{{ report.mark }}">
            </div>

            <button type="submit" class="btn btn-blue w-100 py-2">ثبت نمره و بایگانی کردن</button>
        </form>
    </div>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/List Reports.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}گزارشات و تکالیف{% endblock %}
{% block content %}
<!-- بخش اصلی صفحه -->
<section class="main active-side">
    <!-- جدول لیست گزارش ها -->
    <div class="container reports">
        <table class="table table-primary table-striped list-reports mx-1">
            <!-- منو -->
            <tr>
                <th>نام</th>
                <th>نام خانوادگی</th>
                <th>شماره گزارش</th>
                <th>فایل</th>
                <th>نمره</th>
                <th>نمایش</th>
            </tr>
            <!-- بدنه و ایتم ها -->
            {% for report in reports %}
            <tr>
                <td>{{ report.student.firstname }}</td>
                <td>{{ report.student.lastname }}</td>
                <td>{{ report.number }}</td>
                <td>
                    {% if report.file %}
                    <a href="{{ report.file.url }}">دانلود</a>
                    {% else %}
                    <span>-</span>
                    {% endif %}
                </td>
                <td>
                    {% if report.mark %}
                    <span>{{ report.mark }}</span>
                    {% else %}
                    <span>-</span>
                    {% endif %}
                </td>
                <td>
                    <a href="/teachers/reports_list/{{ report.id }}"> نمایش </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <!-- فرم باز و بسته کردن تکالیف -->
    <form class="form" method="post">
        {% csrf_token %}
        <p class="small">فعال کردن و غیر فعال کردن گرازش های دانشجو.</p>
        <div class="row">
            <div class="col-md">
                {% for part_active in report_parts %}
                <div class="form-check form-switch mb-2">
                    <input name="report_number" class="form-check-input" type="checkbox" id="goz{{ part_active.number }}" value="{{ part_active.id }}" {% if part_active.is_active %} checked {% endif %}>
                    <label class="form-check-label" for="goz1"> گزارش {{ part_active.number }} </label>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- دکمه ثبت -->
        <button type="submit" class="btn btn-blue w-50 py-2 mb-1">ثبت</button>
    </form>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/List Students.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}لیست دانشجویان{% endblock %}
{% block content %}
<!-- بخش اصلی صفحه -->
<section class="main active-side">
    <table class="table table-primary table-striped list-students">
        <!-- منو -->
        <tr>
            <th>ردیف</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th>پروژه</th>
            <th>عملیات</th>
        </tr>
        <!-- بدنه و ایتم ها -->
        {% for student in students %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>{{ student.firstname }}</td>
            <td>{{ student.lastname }}</td>
            <td>{{ student.project.title }}</td>
            <td>
                <a href="/teachers/students-list/delete/{{ student.id }}">
                    <i class="bi bi-trash-fill text-danger"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/List Suggestions.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}لیست پیشنهادات{% endblock %}
{% block content %}
<!-- بخش اصلی صفحه -->
<section class="main active-side">
    <div class="container Suggestions">
        <table class="table table-primary table-striped list-Suggestions mx-1 text-center">
            <!-- منو -->
            <tr>
                <th>نام</th>
                <th>نام خانوادگی</th>
                <th>پروژه</th>
                <th>پلتفرم</th>
                <th>تعداد اعضا</th>
                <th>توضیحات</th>
                <th>عملیات</th>
            </tr>
            <!-- بدنه و ایتم ها -->
            {% for suggestion in suggestions %}
            <tr>
                <td>{{ suggestion.creator.first_name }}</td>
                <td>{{ suggestion.creator.last_name }}</td>
                <td>{{ suggestion.title }}</td>
                <td>{{ suggestion.get_type_display }}</td>
                <td>{{ suggestion.get_number_of_students_display }}</td>
                <td>{{ suggestion.description }}</td>
                <td>
                    <a class="btn btn-primary" href="/teachers/suggestions-list/confirm/{{ suggestion.id }}">
                        <i class="bi bi-check px-1"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/List projects.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}لیست پروژه‌ها{% endblock %}
{% block content %}
<!-- بخش اصلی صفحه -->
<section class="main active-side">
    <div class="list-group list-group-checkable  gap-2 w-auto">
        <!-- ایتم های انتخاب پروژه -->
        {% for project in projects %}
        <div>
            <label class="list-group-item rounded-3 py-3">
                <span>{{ project.title }}</span>
                <div class="small opacity-50 d-flex justify-content-between">
                    <span>{{ project.get_type_display  }}</span>
                    <span> <strong>{{ project.get_number_of_students_display }}</strong> نفره </span>
                </div>
            </label>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/Parts Project.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}ایجاد پروژه{% endblock %}
{% block content %}
<!-- بخش اصلی -->
<section class="main active-side">
    <!-- فرم -->
    <form class="form" method="post">
        {% csrf_token %}
        <p class="small">فعال کردن و غیر فعال کردن بخش های منوی دانشجو.</p>
        <div class="form-check form-switch mb-2">
            <input name="can_get" class="form-check-input" type="checkbox" role="switch" id="akhz" {% if settings.can_get %} checked {% endif %}>
            <label class="form-check-label" for="akhz">اخذ پروژه</label>
        </div>
        <div class="form-check form-switch mb-2">
            <input name="suggest" class="form-check-input" type="checkbox" role="switch" id="pish" {% if settings.suggest %} checked {% endif %}>
            <label class="form-check-label" for="pish">پیشنهاد موضوع پروژه</label>
        </div>
        <div class="form-check form-switch mb-2">
            <input name="reports" class="form-check-input" type="checkbox" role="switch" id="gozarsh" {% if settings.reports %} checked {% endif %}>
            <label class="form-check-label" for="gozarsh">گزارش ها وتکالیف</label>
        </div>
        <div class="form-check form-switch mb-3">
            <input name="final_report" class="form-check-input" type="checkbox" role="switch" id="gozarsh_final" {% if settings.final_report %} checked {% endif %}>
            <label class="form-check-label" for="gozarsh_final">گزارش نهایی</label>
        </div>
        <!-- دکمه ثبت -->
        <button type="submit" class="btn btn-blue w-50 py-2 mb-1">ثبت</button>
    </form>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/Reports.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}گزارشات{% endblock %}
{% block content %}
<!-- بخش اصلی پروژه -->
<section class="main active-side">
    <div class="form">
        <!-- اطلاعات -->
        <h5 class="mb-3">{{ report.student.firstname }} {{ report.student.lastname }}</h5>
        <p>
            <p class="small bg-primary text-light p-1 rounded d-inline">
                گزارش {{ report.number }}
            </p>
            <br><br>
            فایل ها
            <br>

        </p>
        <!-- فایل ها -->
        <div class="file-drop-area mb-3">
            {% if report.file %}
            <a href="{{ report.file.url }}">{{ report.file }}</a>
            {% else %}
            <span>فایلی موجود نیست</span>
            {% endif %}
        </div>
        <!-- توضیحات -->
        <div class="mb-3">
            <label for="PrpjectDiscripiton" class="form-label">توضیحات اختیاری</label>
            <textarea class="form-control" id="PrpjectDiscripiton" cols="5" rows="4" disabled>{{ report.description }}</textarea>
        </div>
        <!-- فرم ثبت نمره -->
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="PrpjectDiscripiton" class="form-label">نمره</label>
                <input name="mark" type="number" class="form-control w-25" placeholder="ندارد" min="0" max="20" value="{{ report.mark }}">
            </div>
            <button type="submit" class="btn btn-blue w-25 py-2">ثبت نمره</button>
        </form>
        </table>
    </div>
</section>
{% endblock %}

Management of student projects/teachers/templates/teachers/project.html
{% extends 'teachers/includes/_layout.html' %}
{% load static %}
{% block title %}پروژه{% endblock %}
{% block content %}
<!-- بخش اصلی -->
<section class="main active-side">
    <form class="form">
        <!-- عنوان پروژه -->
        <div class="mb-3">
            <label for="PrpjectName" class="form-label">عنوان پروژه</label>
            <input type="text" class="form-control" id="PrpjectName" placeholder="پروژه فلان">
        </div>
        <!-- انتخاب پلتفرم و تعداد نفرات گروه -->
        <div class="d-flex flex-column flex-md-row justify-content-center mb-3">
            <!-- پلتفرم -->
            <div class="list-group m-1 w-auto">
                <!-- web -->
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="checkbox" value="" checked>
                    <span>
                        تحت وب
                        <span class="d-block text-muted small">سایت ها و وبسایت هایی که از طریق اینترنت قایل دسترسی
                            هستند</span>
                    </span>
                </label>
                <!-- desktop -->
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="checkbox" value="">
                    <span>
                        دسکتاپ
                        <span class="d-block text-muted small">نرم افزار های ویندوزی برای لپ تاپ و کامپیوتر</span>
                    </span>
                </label>
                <!-- mobile -->
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="checkbox" value="" checked>
                    <span>
                        موبایل
                        <span class="d-block text-muted small">اپیکیشن اندروید برای گوشی های موبایل</span>
                    </span>
                </label>
            </div>
            <!-- تعداد گروه -->
            <div class="list-group m-0 mt-1  w-auto">
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="Radios" id="radios1" value="1">
                    <span>
                        1 نفر
                    </span>
                </label>
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="Radios" id="radios2" value="2" checked>
                    <span>
                        2 نفر
                    </span>
                </label>
                <label class="list-group-item d-flex gap-2">
                    <input class="form-check-input" type="radio" name="Radios" id="radios3" value="3">
                    <span>
                        3 نفر
                    </span>
                </label>
            </div>
        </div>
        <!-- توضیحات پروژه -->
        <div class="mb-3">
            <label for="PrpjectName" class="form-label">توضیحات پروژه</label>
            <textarea class="form-control" id="PrpjectInfo" cols="5" rows="4" placeholder="این پروژه دو نفره است و گروه های دو نفره میتوانند با کمک  هم این پروژه رو انجام بدن"></textarea>
        </div>
        <!-- دکمه ثبت -->
        <button type="button" class="btn btn-blue w-100 py-2 mb-1">ویرایش</button>
        <!-- دکمه پروژه های ایجاد شده -->
        <button type="button" class="btn btn-secondary w-100 py-2 mb-1">حذف</button>
    </form>
</section>
{% endblock %}